import { Button } from '@shared/ui';
import { useNavigate } from 'react-router-dom';
import { useReports } from '../../hooks';
import { ProjectReportCard } from '../../components/ProjectReportCard';

export function ClientReportsPage() {
  const navigate = useNavigate();
  const { data: reports, isLoading } = useReports();

  const handleViewReport = (reportId: string) => {
    navigate(`/reports/${reportId}`);
  };

  const unreadReports = reports?.filter((r) => r.viewCount === 0) || [];

  if (isLoading) {
    return <div style={{ padding: '24px' }}>Loading reports...</div>;
  }

  return (
    <div style={{ padding: '24px', maxWidth: '1200px', margin: '0 auto' }}>
      <div style={{ marginBottom: '32px' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <div>
            <h1 style={{ fontSize: '32px', fontWeight: 'bold', marginBottom: '8px' }}>
              My Reports
            </h1>
            <p style={{ color: '#666' }}>
              {unreadReports.length > 0
                ? `You have ${unreadReports.length} unread report${
                    unreadReports.length > 1 ? 's' : ''
                  }`
                : 'All reports are up to date'}
            </p>
          </div>
          <Button variant="ghost" onClick={() => navigate('/dashboard')}>
            Back to Home
          </Button>
        </div>
      </div>

      {reports?.length === 0 ? (
        <div
          style={{
            padding: '64px',
            textAlign: 'center',
            border: '2px dashed #ddd',
            borderRadius: '8px',
          }}
        >
          <p style={{ fontSize: '18px', color: '#999', marginBottom: '8px' }}>
            No reports available yet.
          </p>
          <p style={{ fontSize: '14px', color: '#ccc' }}>
            Your reports will appear here once they are generated by the admin.
          </p>
        </div>
      ) : (
        <div
          style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))',
            gap: '20px',
          }}
        >
          {reports?.map((report) => (
            <ProjectReportCard
              key={report.id}
              report={report}
              onView={() => handleViewReport(report.id)}
            />
          ))}
        </div>
      )}
    </div>
  );
}
